
POST http://localhost:5000/users/signup HTTP/1.1
Content-Type: application/json

{ 
  "name": "siuu",
  "email": "siuuu@gmail.com",
  "password": "bye360",
  "type":"TEACHER"
}

###
POST  http://localhost:5000/users/signin HTTP/1.1
Content-Type: application/json

{ 
  "email": "faizan@gmail.com",
  "password": "faizan360"
}

###

POST  http://localhost:5000/student/create HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsb0BnbWFpbC5jb20iLCJpZCI6ImFiOTM2OWFhLWM0Y2YtNDQ5Yi1hMjFmLTM3ZGQ2NWQ4ODBmMCIsInR5cGUiOiJTVFVERU5UIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2ODc2MjgwNDV9.Xgo7zmykWY_aqR5vBDKVPGh_lnHc6PHdUzHG56Ua_P0

{ 
  "bio": "ok bye",
  "education": "8 pass"
}

###
POST http://localhost:5000/users/signup HTTP/1.1
Content-Type: application/json

{ 
  "name": "teacher",
  "email": "teacher@gmail.com",
  "password": "alo360",
  "type":"TEACHER"
}

###
POST  http://localhost:5000/users/signin HTTP/1.1
Content-Type: application/json

{ 
  "email": "teacher@gmail.com",
  "password": "alo360"
}

###

POST  http://localhost:5000/student/create HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsb0BnbWFpbC5jb20iLCJpZCI6ImFiOTM2OWFhLWM0Y2YtNDQ5Yi1hMjFmLTM3ZGQ2NWQ4ODBmMCIsInR5cGUiOiJTVFVERU5UIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2ODc2MjgwNDV9.Xgo7zmykWY_aqR5vBDKVPGh_lnHc6PHdUzHG56Ua_P0

{ 
  "bio": "ok bye",
  "education": "8 pass"
}



# simple string -> jumbled1 !=> string
# single string -> jumbled2 |comp(jumbled1,jumbled2)
# create course
# token created at backend => sent to front end


# /customer/user_id
###

POST  http://localhost:5000/tutor/tutorcreate HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpdXV1QGdtYWlsLmNvbSIsImlkIjoiZTRhZWYzYTEtOTI0Yi00MTcxLTkzOTUtNTk5NzI3NjA4YjJiIiwidHlwZSI6IlRFQUNIRVIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTY4NzY5MzgzM30.lHzoCB5eFbRaUQl5HGwsiLSO1Q63yToiRPyS_fOwOqk

{ 
  "bio": "ronaldo",
  "education": "no idea"
}



###

PATCH   http://localhost:5000/tutor/tutorupdate HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwiaWQiOiIyNGIzYmJlMC03ZDY2LTQyNDUtYTE1Mi1iOWJmMzg1MDNhMzQiLCJ0eXBlIjoiVEVBQ0hFUiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNjg3NjI4MzA2fQ.hY2M7VGF2dqz4i6406e6nXjD9CubHk9W192yRAlliek

{ 
  "password":"anik1200",
  "bio": "abrarabedin@1google.com",
  "education": "123456"
}



# ###

# DELETE   http://localhost:5000/tutor/tutordelete HTTP/1.1
# Content-Type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lc3NpQGdtYWlsLmNvbSIsImlkIjoiNmIyMWVkZDctNWU1NC00ZGQwLTk3MzAtYmVmMjg1ODYwMjE3IiwidHlwZSI6IlRFQUNIRVIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTY4NzYxNzg0NH0.iJKMzzRjr3nXb1TbM_JEUe_9NH9dfvsnhJdqVrAIh4Q

# { 
#   "password":"anik1200",
#   "bio": "abrarabedin@google.com",
#   "education": "123456"
# }

###

PATCH   http://localhost:5000/student/update HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsb0BnbWFpbC5jb20iLCJpZCI6ImFiOTM2OWFhLWM0Y2YtNDQ5Yi1hMjFmLTM3ZGQ2NWQ4ODBmMCIsInR5cGUiOiJTVFVERU5UIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2ODc2MjgwNDV9.Xgo7zmykWY_aqR5vBDKVPGh_lnHc6PHdUzHG56Ua_P0

{ 
  "password":"alo9009",
  "bio": "daddy",
  "education": "pro developer"
}



//course

###

POST  http://localhost:5000/course/coursepost HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsb0BnbWFpbC5jb20iLCJpZCI6ImFiOTM2OWFhLWM0Y2YtNDQ5Yi1hMjFmLTM3ZGQ2NWQ4ODBmMCIsInR5cGUiOiJTVFVERU5UIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2ODc2MjgwNDV9.Xgo7zmykWY_aqR5vBDKVPGh_lnHc6PHdUzHG56Ua_P0

{
  "title":"eee111-2023","description":"description","seatStatus":5,
            "address":"dhaka","endDate":"2023-07-25T10:57:45.593Z",
            "categories":"eee",
            "teacherProfileId":"79696de7-47a1-4d06-a24a-711ba64ab5ed"
        }

###

GET  http://localhost:5000/course/categories HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsb0BnbWFpbC5jb20iLCJpZCI6ImFiOTM2OWFhLWM0Y2YtNDQ5Yi1hMjFmLTM3ZGQ2NWQ4ODBmMCIsInR5cGUiOiJTVFVERU5UIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2ODc2MjgwNDV9.Xgo7zmykWY_aqR5vBDKVPGh_lnHc6PHdUzHG56Ua_P0

{
  "query":"phy"
}

###

GET  http://localhost:5000/course/showcourse HTTP/1.1
Content-Type: application/json



###

PATCH   http://localhost:5000/course/courseupdate/c4ba8b9a-fb8b-439e-9b5c-6d0a1a3801f5 HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsb0BnbWFpbC5jb20iLCJpZCI6ImFiOTM2OWFhLWM0Y2YtNDQ5Yi1hMjFmLTM3ZGQ2NWQ4ODBmMCIsInR5cGUiOiJTVFVERU5UIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2ODc2MjgwNDV9.Xgo7zmykWY_aqR5vBDKVPGh_lnHc6PHdUzHG56Ua_P0

{
      "description": "phy111 faltu course",
      "seatStatus": 100,
      "address": "i love u",
      "endDate": "2050-07-25T10:57:45.593Z"
}
//single course

###

GET  http://localhost:5000/course/singlecourse/c4ba8b9a-fb8b-439e-9b5c-6d0a1a3801f5 HTTP/1.1
Content-Type: application/json



###



//enroll course

###

POST  http://localhost:5000/enrollcourse/enroll HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsb0BnbWFpbC5jb20iLCJpZCI6ImFiOTM2OWFhLWM0Y2YtNDQ5Yi1hMjFmLTM3ZGQ2NWQ4ODBmMCIsInR5cGUiOiJTVFVERU5UIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2ODc2MjgwNDV9.Xgo7zmykWY_aqR5vBDKVPGh_lnHc6PHdUzHG56Ua_P0

{
  "studentProfileId":"99db62ee-c23d-49f8-9395-045680b31491",
  "courseId":"9eeb036e-43ab-449a-b439-334ebe7b41d5"
}


###
GET   http://localhost:5000/enrollcourse/enrolledcourses HTTP/1.1
Content-Type: application/json

{
  "studentProfileId":"99db62ee-c23d-49f8-9395-045680b31491"
}

###
DELETE   http://localhost:5000/enrollcourse/unenroll HTTP/1.1
Content-Type: application/json

{
  "id":"ed1a251e-e090-47ef-a044-41046d806d2c"
}




