
POST http://localhost:5000/users/signup HTTP/1.1
Content-Type: application/json

{ 
  "name": "abrar",
  "email": "abrarabedin@slkdjf1234.sdfj",
  "password": "123456"
}

###
POST  http://localhost:5000/users/signin HTTP/1.1
Content-Type: application/json

{ 
  "email": "abrarabedin@slkdjf123.sdfj",
  "password": "123456"
}

###

POST  http://localhost:5000/student/create HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFicmFyYWJlZGluQHNsa2RqZjEyMzQuc2RmaiIsImlkIjoiNjhhNGQ4ZGYtM2NiZC00MTBjLWJmYzgtMzAxZjNhZGQ1NzlhIiwiaWF0IjoxNjg3NTUyNjMwfQ.pY8l2b_e1H-QLdg9dz6wk6InllFV6jDCcepCDRW-V6o

{ 
  "bio": "abrarabedin@slkdjf12.sdfj",
  "education": "123456"
}


# simple string -> jumbled1 !=> string
# single string -> jumbled2 |comp(jumbled1,jumbled2)
# create course
# token created at backend => sent to front end


# /customer/user_id