
POST http://localhost:5000/users/signup HTTP/1.1
Content-Type: application/json

{ 
  "name": "Anik",
  "email": "anik@gmail.com",
  "password": "anik69"
}

###
POST  http://localhost:5000/users/signin HTTP/1.1
Content-Type: application/json

{ 
  "email": "abrarabedin@slkdjf123.sdfj",
  "password": "123456"
}

###

POST  http://localhost:5000/student/create HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFicmFyYWJlZGluQHNsa2RqZjEyMzQuc2RmaiIsImlkIjoiODg1NDdkMjUtYmQwMi00NDRjLWIzODUtZjJjMDRkMjRiMjQ2IiwiaWF0IjoxNjg3NTUzMzA2fQ.U4Dki8WEFIMo1jxXSkHTR5evv9vK4NOIF9MI26aa1ME

{ 
  "bio": "abrarabedin@slkdjf12.sdfj",
  "education": "123456"
}



###
POST  http://localhost:5000/tutor/tutorcreate HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuaWtAZ21haWwuY29tIiwiaWQiOiJiMGRhM2ViMi0zN2U1LTQyMTQtOGU3Yi1iZTI0N2UyNDFiNmQiLCJpYXQiOjE2ODc1NTQ4MjB9.CnYumgxLjaOfBRKSkwYCtb5fF4cXg55fW-a4bZNLbEY

{ 
  "bio": "teach biology",
  "education": "phd. biology"
}